- name: installing datastax enterprise
  apt: pkg=dse-full state=installed update-cache=yes
  register: dse

- name: configuring datastax enterprise
  template: src=templates/cassandra.yaml dest=/etc/dse/cassandra/cassandra.yaml

- name: configure templates/cassandra-env.sh
  template: src=templates/cassandra-env.sh dest=/etc/dse/cassandra/cassandra-env.sh

- name: create /etc/cassandra dir
  file:
    path: /etc/cassandra
    state: directory
    mode: 0755

- name: configure pass jmxremote.password
  template: src=templates/jmxremote.password dest=/etc/cassandra/jmxremote.password
