---
- hosts: [ "nd1", "nd2", "nd3"]
  user: vagrant
  become: yes
  tasks:

  - include: tasks/dependencies.yml
  - include: tasks/zabbix-server.yml
  - include: tasks/zabbix-ubuntu.yml
  - include: tasks/cassandra-docker.yml
#  - include: tasks/cassandra-docker.yml

