#  basic
---
- hosts: vault
  gather_facts: False 

  become: true
  become_method: sudo
  become_user: root

  tasks:

    - name: apt-get update 
      raw: apt-get update -qq 
    - name: Install python 2.7 
      raw: apt-get install -qq python2.7
