# zabbix-ubuntu 16.04
---
- hosts: ["node1", "node2", "node3"]
  user: vagrant
  become: yes

  tasks:

  - name: Install a .deb package from the internet.
    apt:
       deb: http://repo.zabbix.com/zabbix/3.2/ubuntu/pool/main/z/zabbix-release/zabbix-release_3.2-1+xenial_all.deb
       update_cache: yes

#  - shell: wget http://repo.zabbix.com/zabbix/3.2/ubuntu/pool/main/z/zabbix-release/zabbix-release_3.2-1+xenial_all.deb
#  - shell: dpkg -i zabbix-release_3.2-1+xenial_all.deb

  - name: updating cache
    apt: update_cache=yes

  - name: Install zabbix-agent from repo
    apt: name=zabbix-agent

  - template: >
      src=./templates/zabbix.j2 
      dest=/etc/zabbix/zabbix_agentd.conf
      owner=root
      group=root
      mode=0644
      backup=yes
  
  - template: >
      src=./templates/zabbix_params_cassandra.j2
      dest=/etc/zabbix/zabbix_agentd.d/userparameters_cassandra.conf
      owner=root
      group=root
      mode=0644
  
  - service: name=zabbix-agent enabled=yes
  - service: name=zabbix-agent state=started
  - service: name=zabbix-agent state=restarted

  - name: Install socat from repo
    apt: name=socat

  - template: >
      src=./templates/socat.service
      dest=/etc/systemd/system/socat.service
      owner=root
      group=root
      mode=0644

  - service: name=socat enabled=yes
  - service: name=socat state=started


  - cron:
      name: "nodetool info"
      user: "root"
      minute: "*"
      hour: "*"
      day: "*"
      month: "*"
      job: "nodetool info > /tmp/nodetool_info.tmp; cp -f /tmp/nodetool_info.tmp /tmp/nodetool_info"

  - cron:
      name: "nodetool tablestats system"
      user: "root"
      minute: "*"
      hour: "*"
      day: "*"
      month: "*"
      job: "nodetool tablestats system > /tmp/nodetool_tablestats_system.tpm; cp -f /tmp/nodetool_tablestats_system.tpm /tmp/nodetool_tablestats_system"
      # job: "nodetool tablestats system > /tmp/nodetool_tablestats_system"

  - cron:
      name: "nodetool tpstats"
      user: "root"
      minute: "*"
      hour: "*"
      day: "*"
      month: "*"
      job: "nodetool tpstats > /tmp/nodetool_tpstats.tpm; cp -f /tmp/nodetool_tpstats.tpm /tmp/nodetool_tpstats"

