- name: copy local registry cert file
  template: >
    src=./templates/registry.vensder.crt
    dest=/usr/local/share/ca-certificates/registry.vensder.crt
    owner=root
    group=root
    mode=0644

- name: update ca certs
  raw: sudo update-ca-certificates

- name: restart docker service
  service:
    name: docker
    state: restarted

# 10.66.40.242	registry.vensder
- lineinfile:
    path: /etc/hosts
    regexp: '^10\.66\.40\.242'
    line: '10.66.40.242	registry.vensder'
    owner: root
    group: root
    mode: 0644

- name: copy template cassandra-env.sh to host
  template: >
    src=./templates/cassandra-env.sh
    dest=/home/vagrant/cassandra-env.sh
    owner=vagrant
    group=vagrant
    mode=0644

- name: copy template docker-compose-cassandra.yml to host
  template: >
    src=./templates/docker-compose-cassandra.yml
    dest=/home/vagrant/docker-compose-cassandra.yml
    owner=vagrant
    group=vagrant
    mode=0644

- name: starting cassandra from docker-compose-cassandra file
  raw: docker-compose -f /home/vagrant/docker-compose-cassandra.yml up -d

- name: copy cassandra-env.sh to docker container
  raw: docker cp /home/vagrant/cassandra-env.sh my-cassandra:/etc/cassandra/cassandra-env.sh

- name: restart docker container
  raw: docker-compose -f /home/vagrant/docker-compose-cassandra.yml restart my-cassandra
