version: '2'
services:
  zabbix-server:
    image: zabbix/zabbix-server-mysql:alpine-3.2.5
    ports:
     - "10051:10051"
    links:
     - mysql-server:mysql-server
     - zabbix-java-gateway:zabbix-java-gateway
    ulimits:
      nproc: 65535
      nofile:
       soft: 20000
       hard: 40000
    mem_limit: 256m
    env_file:
     - .env_db_mysql
     - .env_srv
    user: root
  

  zabbix-web-nginx-mysql:
    image: zabbix/zabbix-web-nginx-mysql:alpine-3.2-latest
    ports:
     - "8081:80"
     - "8443:443"
    links:
     - mysql-server:mysql-server
     - zabbix-server:zabbix-server
    mem_limit: 128m
    env_file:
     - .env_db_mysql
     - .env_web
    user: root


  zabbix-java-gateway:
    image: zabbix/zabbix-java-gateway:alpine-3.2-latest
    ports:
     - "10052:10052"
    env_file:
     - .env_java
    user: root


  mysql-server:
    image: mysql:5.7
    env_file:
     - .env_db_mysql
    user: root

