version: '2'
services:
  my-cassandra:
    image: registry.vensder/cassandra:3.11.0
    container_name: my-cassandra
    restart: always
    environment:
      CASSANDRA_BROADCAST_ADDRESS: {{ config.listen_address }}
      CASSANDRA_RPC_ADDRESS:
      CASSANDRA_SEEDS: '{{ config.seeds }}'
      CASSANDRA_CLUSTER_NAME: {{ config.cluster_name }}
      CASSANDRA_NUM_TOKENS: 32
    ports: 
     - 7000:7000
     - 7001:7001
     - 7199:7199
     - 9042:9042
